#!/usr/bin/env node
/**
 * Generate assets/brand/acb-logo.svg: the robot ACB letters, still, inside a
 * glass cube that spins around them. SMIL can't do 3D, so the cube is
 * projected here at 10° steps and the browser interpolates between them.
 * A quarter turn per loop is seamless because the cube is symmetric, so
 * the final frame is identical to the first and the cube simply stops.
 * Every animation is finite: an endless one keeps the blur filters
 * re-rasterising each frame, which costs battery on phones.
 *
 * The header/favicon logo (acb-logo-static.svg, a letter block) is drawn by
 * hand; its PNG renders (favicons, apple-touch icon, og-image) are made from
 * it in a browser.
 *
 * Run: node scripts/generate-logo.mjs
 */
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const OUT = resolve(import.meta.dirname, "../assets/brand/acb-logo.svg");
const DUR = 2.5; // seconds per quarter turn
const STEPS = 9; // keyframes per quarter turn
const LOOPS = 2; // quarter turns before the cube comes to rest
const CAM = 5.6; // camera distance, in half cube widths
const FOCAL = 700;
const CY = 236; // cube centre y
const TILT = (-24 * Math.PI) / 180; // look down on the cube
const LIGHT = norm([-0.5, 0.6, -0.62]);

const VERTS = [];
for (const x of [-1, 1]) for (const y of [-1, 1]) for (const z of [-1, 1]) VERTS.push([x, y, z]);
const FACES = [
	[0, 1, 3, 2],
	[4, 6, 7, 5],
	[0, 4, 5, 1],
	[2, 3, 7, 6],
	[0, 2, 6, 4],
	[1, 5, 7, 3],
];

function norm(v) {
	const l = Math.hypot(...v);
	return v.map((c) => c / l);
}
const dot = (a, b) => a[0] * b[0] + a[1] * b[1] + a[2] * b[2];

/** Turn by `yaw` about the vertical axis, then tilt towards the camera. */
function rotate([x, y, z], yaw) {
	const [x1, z1] = [x * Math.cos(yaw) + z * Math.sin(yaw), -x * Math.sin(yaw) + z * Math.cos(yaw)];
	return [x1, y * Math.cos(TILT) - z1 * Math.sin(TILT), y * Math.sin(TILT) + z1 * Math.cos(TILT)];
}

/** Per face: projected outline, whether it faces the camera, and its light. */
function faces(yaw) {
	const p = VERTS.map((v) => rotate(v, yaw));
	const xy = p.map(([x, y, z]) => [
		Math.round(256 + (FOCAL * x) / (z + CAM)),
		Math.round(CY - (FOCAL * y) / (z + CAM)),
	]);
	return FACES.map((f) => {
		const c = [0, 1, 2].map((i) => f.reduce((s, v) => s + p[v][i], 0) / 4);
		const n = norm(c);
		const front = dot(n, [c[0], c[1], c[2] + CAM]) < 0;
		return {
			d: `M${f.map((v) => xy[v].join(" ")).join("L")}Z`,
			front,
			light: front ? Math.max(0, dot(n, LIGHT)) : 0,
		};
	});
}

/** Exact moments (to 0.1°) a face turns towards or away from the camera. */
function flips(i) {
	const values = [];
	const times = [];
	for (let j = 0; j <= 900; j++) {
		const v = faces(((j / 900) * Math.PI) / 2)[i].front ? "1" : "0";
		if (values.at(-1) !== v) {
			values.push(v);
			times.push(Number((j / 900).toPrecision(4)));
		}
	}
	return { values: values.join(";"), times: times.join(";") };
}

const anim = `dur="${DUR}s" repeatCount="${LOOPS}" fill="freeze"`;
const frames = Array.from({ length: STEPS + 1 }, (_, k) => faces(((k / STEPS) * Math.PI) / 2));
const paths = [];
const front = [];
for (let i = 0; i < 6; i++) {
	paths.push(
		`<path id="f${i}"><animate attributeName="d" values="${frames.map((f) => f[i].d).join(";")}" ${anim}/></path>`,
	);
	const flip = flips(i);
	if (flip.values === "0") continue; // never faces the camera
	const glass = frames
		.map((f) => (f[i].front ? (0.03 + 0.2 * f[i].light ** 3).toFixed(2) : "0"))
		.join(";");
	const edge =
		flip.values === "1"
			? ""
			: `<animate attributeName="stroke-opacity" values="${flip.values}" keyTimes="${flip.times}" calcMode="discrete" ${anim}/>`;
	front.push(
		`<use href="#f${i}"><animate attributeName="fill-opacity" values="${glass}" ${anim}/>${edge}</use>`,
	);
}

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-label="agentchatbox">
  <title>agentchatbox</title>
  <!-- Generated by scripts/generate-logo.mjs; edit that, not this. -->
  <style>
    /* The cube fades in and spins to a stop; the letters draw in, the visor
       pops, the eyes light, then pulse and blink twice before everything
       rests. The page shows reduced-motion users the still letter block
       (acb-logo-static.svg) instead. */
    .acb-cube { animation: acb-fade .6s ease-out backwards; }
    .acb-draw { animation: acb-draw .6s cubic-bezier(.2, .7, .3, 1) backwards; }
    .acb-a { animation-delay: .35s; }
    .acb-c { animation-duration: .8s; animation-delay: .65s; }
    .acb-b { animation-delay: 1.1s; }
    .acb-smile { animation-duration: .4s; animation-delay: 2.3s; }
    .acb-visor { transform-box: fill-box; transform-origin: center; animation: acb-pop .45s ease-out 1.55s backwards; }
    .acb-eyes { animation: acb-fade .3s ease-out 2s backwards; }
    .acb-glow { transform-box: fill-box; transform-origin: center; animation: acb-pulse 2.4s ease-in-out 2.3s 2 forwards; }
    .acb-blink { transform-box: fill-box; transform-origin: center; animation: acb-blink 4s ease-in-out 2.7s 2; }
    @keyframes acb-draw { from { stroke-dasharray: 100; stroke-dashoffset: 100; } to { stroke-dasharray: 100; stroke-dashoffset: 0; } }
    @keyframes acb-pop { from { opacity: 0; transform: scale(.85); } }
    @keyframes acb-fade { from { opacity: 0; } }
    @keyframes acb-pulse { 0%, 100% { opacity: .2; transform: scale(.85); } 50% { opacity: 1; transform: scale(1.15); } }
    @keyframes acb-blink { 0%, 56%, 66%, 100% { transform: scaleY(1); } 61% { transform: scaleY(.08); } }
  </style>
  <defs>
    <linearGradient id="edge" x1="0" y1="60" x2="0" y2="440" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#5ffff0"/><stop offset=".55" stop-color="#3d9bff"/><stop offset="1" stop-color="#4a63ff"/></linearGradient>
    <linearGradient id="glass" x1="80" y1="60" x2="430" y2="440" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#1ffce4"/><stop offset="1" stop-color="#3a55e8"/></linearGradient>
    <linearGradient id="silver" x1="0" y1="140" x2="0" y2="290" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#fff"/><stop offset="1" stop-color="#8fd9ff"/></linearGradient>
    <radialGradient id="floor"><stop offset="0" stop-color="#3d9bff" stop-opacity=".5"/><stop offset="1" stop-color="#3d9bff" stop-opacity="0"/></radialGradient>
    <radialGradient id="eye-glow"><stop offset="0" stop-color="#2ffff0" stop-opacity=".95"/><stop offset="1" stop-color="#2ffff0" stop-opacity="0"/></radialGradient>
    <filter id="glow" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="9" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
    <filter id="bloom" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="7" result="b"/><feColorMatrix in="b" type="matrix" values="0 0 0 0 .18  0 0 0 0 .95  0 0 0 0 .9  0 0 0 .75 0" result="c"/><feMerge><feMergeNode in="c"/><feMergeNode in="SourceGraphic"/></feMerge></filter>
    ${paths.join("\n    ")}
  </defs>
  <ellipse cx="256" cy="458" rx="190" ry="26" fill="url(#floor)"><animate attributeName="opacity" values=".6;1;.6" ${anim}/></ellipse>
  <!-- Back of the cube (all faces, dim), then the letters, then the front glass. -->
  <g class="acb-cube" fill="url(#glass)" fill-opacity=".07" stroke="url(#edge)" stroke-width="5" stroke-opacity=".35" stroke-linejoin="round">
    ${[0, 1, 2, 3, 4, 5].map((i) => `<use href="#f${i}"/>`).join("")}
  </g>
  <!-- The letters are the robot: C is the head, A and B flank it. -->
  <g transform="translate(256 244) scale(.56) translate(-227 -216)" filter="url(#bloom)">
    <path class="acb-draw acb-a" pathLength="100" d="M40 288L95 144L150 288M62 240H128" fill="none" stroke="url(#silver)" stroke-width="24" stroke-linecap="round" stroke-linejoin="round"/>
    <path class="acb-draw acb-c" pathLength="100" d="M315 174.7A72 72 0 1 0 315 257.3" fill="none" stroke="url(#silver)" stroke-width="26"/>
    <path class="acb-draw acb-b" pathLength="100" d="M350 144V288M350 144H372A34 34 0 0 1 372 212H350M350 212H376A38 38 0 0 1 376 288H350" fill="none" stroke="url(#silver)" stroke-width="24" stroke-linecap="round" stroke-linejoin="round"/>
    <rect class="acb-visor" x="210" y="186" width="92" height="52" rx="20" fill="#04122c" stroke="url(#silver)" stroke-width="4"/>
    <g class="acb-eyes">
      <circle class="acb-glow" cx="237" cy="210" r="20" fill="url(#eye-glow)"/>
      <circle class="acb-glow" cx="275" cy="210" r="20" fill="url(#eye-glow)"/>
      <g class="acb-blink">
        <ellipse cx="237" cy="210" rx="9" ry="12" fill="#3dfff0"/>
        <ellipse cx="275" cy="210" rx="9" ry="12" fill="#3dfff0"/>
        <circle cx="234" cy="205" r="2.5" fill="#fff" fill-opacity=".9"/>
        <circle cx="272" cy="205" r="2.5" fill="#fff" fill-opacity=".9"/>
      </g>
    </g>
    <path class="acb-draw acb-smile" pathLength="100" d="M243 256Q256 265 269 256" fill="none" stroke="#3dfff0" stroke-width="6" stroke-linecap="round"/>
  </g>
  <g class="acb-cube" fill="url(#glass)" stroke="url(#edge)" stroke-width="9" stroke-linejoin="round" filter="url(#glow)">
    ${front.join("\n    ")}
  </g>
</svg>
`;
await writeFile(OUT, svg);
console.log(`wrote ${OUT} (${svg.length} bytes)`);
